# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a301c32e0a7da38430e826ad429a8a9d4001fda2f075056f32576f6b621c8ec1fde5e835ab484dd1388d44f950e91ee100f2f73aa9cc1e30c5820c915f921f6

test:
  secret_key_base: 2dfdcfef102ed7d1c026345331b8a5ab75c3ca1ba5242fce4c78a7d6bf9fc88dc3ef5701e018936f24ed18a1a7ac9cec13daa2d09ea1d54fc4f7b28ad11fc02a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
